name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install python3-setuptools
          pip3 install wheel 
          pip3 install markdown weasyprint

      - name: Build resume
        run: make resume

      - name: Push dist folder into repository
        run: |
          git add ./dist
          git commit -m "Resume build ($(date +'%H:%M:%S at %D'))"
          git push origin master
